language: python
python:
- "3.6"
- "3.7"
- "3.8"
- "3.9"

install:
  - pip3 install -r requirements-dev.txt
  - pip3 install coveralls
  - python3 setup.py install

script:
  - python3 make.py test

after_success:
  - coveralls
